import React, { useCallback, useEffect, useRef, useState } from "react";
import {
  login as apiLogin,
  register as apiRegister,
  checkUsernameAvailability,
  updateUsername,
} from "../utils/api";
import Cookies from "js-cookie";
import { useUser } from "./UserContext";
import InterstatePopout from "./InterstatePopout";
import InterstateButton from "./InterstateButton";
import { toast } from "react-hot-toast";
import { useTurnkey, ClientState, AuthState } from "@turnkey/react-wallet-kit";
import {
  GoogleOAuthProvider,
  GoogleLogin,
  type CredentialResponse,
} from "@react-oauth/google";
import { sha256 } from "@noble/hashes/sha256";
import { bytesToHex } from "@noble/hashes/utils";
import { useUserLimit } from "./UserLimitContext";
import { ApiError } from "../utils/api";
import { isBotUsername } from "../utils/botUsernames";
import { FiCheck, FiAlertCircle, FiLoader } from "react-icons/fi";
import {
  useWalletDiscovery,
  type DiscoveredWallet,
} from "../hooks/useWalletDiscovery";
import posthog from "posthog-js";

const isDev = process.env.NODE_ENV !== "production";
const ENABLE_EMAIL_AUTH = false;
const AUTH_BUTTON_WIDTH_CLASS = "w-full max-w-[400px] mx-auto";
const SESSION_METADATA_KEY = "@turnkey/session-metadata";

interface LoginModalProps {
  open: boolean;
  onClose: () => void;
  forceLogin?: boolean;
}

// Extend the Window interface to include the solana property
declare global {
  interface Window {
    solana?: any;
    ethereum?: any;
  }
}

const TURNKEY_AUTH_METHOD_EVENT = "turnkey-auth-method";
const TURNKEY_APIKEY_READY_EVENT = "turnkey-apikey-ready";
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;

const recordAuthMethod = (method: "google" | "wallet") => {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("turnkeyLastAuthMethod", method);
    window.dispatchEvent(
      new CustomEvent(TURNKEY_AUTH_METHOD_EVENT, { detail: method }),
    );
  } catch (err) {
    console.warn("[LoginModal] Failed to persist auth method", err);
  }
};

const recordPasskeyReady = () => {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("turnkeyPasskeyReady", "true");
    window.dispatchEvent(new CustomEvent("turnkey-passkey-ready"));
  } catch (err) {
    console.warn("[LoginModal] Failed to persist passkey ready flag", err);
  }
};

export default function LoginModal({
  open,
  onClose,
  forceLogin = false,
}: LoginModalProps) {
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [email, setEmail] = useState("");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [show, setShow] = useState(false);

  // Separate loading states for each login method
  const [loading, setLoading] = useState(false); // For email/password login
  const [googleLoading, setGoogleLoading] = useState(false);
  const [googleNonce, setGoogleNonce] = useState<string | null>(null);
  const pubKeyRef = useRef<string | null>(null);
  const createdNonceRef = useRef(false);
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

  const [error, setError] = useState<string | null>(null);
  const [walletError, setWalletError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const { refreshUser, user, loading: userLoading } = useUser();
  const { setUserLimitReached } = useUserLimit();
  const [wiggle, setWiggle] = useState(false);

  // Username setup step for new users
  const [loginStep, setLoginStep] = useState<"auth" | "username">("auth");
  const [newUsername, setNewUsername] = useState("");
  const [usernameChecking, setUsernameChecking] = useState(false);
  const [usernameSubmitting, setUsernameSubmitting] = useState(false);
  const [usernameValidation, setUsernameValidation] = useState<{
    isValid: boolean;
    isAvailable: boolean | null;
    error: string | null;
  }>({ isValid: false, isAvailable: null, error: null });
  const usernameCheckTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Use Turnkey SDK for wallet authentication
  const turnkey = useTurnkey();
  const authState = turnkey?.authState;
  const clientState = turnkey?.clientState;

  // Dynamic wallet discovery
  const {
    allWallets,
    activeWalletId,
    walletError: discoveryWalletError,
    clearError: clearDiscoveryError,
    connectAndSign,
  } = useWalletDiscovery();

  // Helper function to clear all loading states
  const clearAllLoadingStates = () => {
    setGoogleLoading(false);
    clearDiscoveryError();
    setError(null);
    setWalletError(null);
  };

  // Check if username looks auto-generated (wallet address or similar)
  const isAutoGeneratedUsername = (
    name: string | null | undefined,
  ): boolean => {
    if (!name) return true;
    // Check if it looks like a wallet address (hex or base58)
    if (/^(0x)?[a-fA-F0-9]{40,}$/.test(name)) return true;
    if (/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(name)) return true;
    // Check if it starts with "user_" (auto-generated pattern)
    if (/^user_[a-z0-9]+$/i.test(name)) return true;
    return false;
  };

  // Username format validation
  const validateUsernameFormat = (
    value: string,
  ): { valid: boolean; error: string | null } => {
    if (!value || value.length === 0) {
      return { valid: false, error: null };
    }
    if (value.length < 3) {
      return { valid: false, error: "Username must be at least 3 characters" };
    }
    if (value.length > 20) {
      return { valid: false, error: "Username must be 20 characters or less" };
    }
    const usernameRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
    if (!usernameRegex.test(value)) {
      if (!/^[a-zA-Z_]/.test(value)) {
        return {
          valid: false,
          error: "Username must start with a letter or underscore",
        };
      }
      return {
        valid: false,
        error: "Only letters, numbers, and underscores allowed",
      };
    }
    const reservedWords = [
      "admin",
      "administrator",
      "root",
      "system",
      "interstate",
      "support",
      "help",
      "null",
      "undefined",
    ];
    if (reservedWords.includes(value.toLowerCase()) || isBotUsername(value)) {
      return { valid: false, error: "This username is reserved" };
    }
    return { valid: true, error: null };
  };

  // Handle username input change with debounced availability check
  const handleNewUsernameChange = (value: string) => {
    // Allow uppercase letters - only strip invalid characters
    const cleanValue = value.replace(/[^a-zA-Z0-9_]/g, "");
    setNewUsername(cleanValue);

    // Clear previous timeout
    if (usernameCheckTimeoutRef.current) {
      clearTimeout(usernameCheckTimeoutRef.current);
    }

    // Validate format first
    const formatValidation = validateUsernameFormat(cleanValue);
    if (!formatValidation.valid) {
      setUsernameValidation({
        isValid: false,
        isAvailable: null,
        error: formatValidation.error,
      });
      return;
    }

    // Debounce availability check
    setUsernameChecking(true);
    usernameCheckTimeoutRef.current = setTimeout(async () => {
      try {
        const result = await checkUsernameAvailability(cleanValue);
        setUsernameValidation({
          isValid: result.valid,
          isAvailable: result.available,
          error: result.available ? null : "Username is already taken",
        });
      } catch (err: any) {
        setUsernameValidation({
          isValid: false,
          isAvailable: false,
          error: err?.message || "Failed to check availability",
        });
      } finally {
        setUsernameChecking(false);
      }
    }, 500);
  };

  // Handle username submission
  const handleUsernameSubmit = async () => {
    if (
      !usernameValidation.isValid ||
      !usernameValidation.isAvailable ||
      !user?.bearerToken
    ) {
      return;
    }

    setUsernameSubmitting(true);
    try {
      const result = await updateUsername(user.bearerToken, newUsername);
      if (result.success) {
        await refreshUser();
        toast.success("Username set successfully!");
        // Clear the new user flow ref and signal parent can close
        isInNewUserFlowRef.current = false;
        window.dispatchEvent(new CustomEvent("login-modal-can-close"));
        onClose();
      }
    } catch (err: any) {
      toast.error(err?.message || "Failed to set username");
    } finally {
      setUsernameSubmitting(false);
    }
  };

  // Handle successful login - check if username needs to be set
  const handleSuccessfulLogin = async (isNewUser: boolean = false) => {
    await refreshUser();
    // Give time for user context to update
    setTimeout(() => {
      // Check if user has an auto-generated username
      const currentUser = Cookies.get("token") ? user : null;
      if (isNewUser || isAutoGeneratedUsername(currentUser?.name)) {
        setLoginStep("username");
      } else {
        onClose();
      }
    }, 100);
  };

  // After wallet login, optionally fetch wallets once to populate SDK state (after ensuring session)
  // Accepts optional loginResult to use its session data directly (more reliable than turnkey.session)
  const finalizeWalletLoginSession = useCallback(async (_loginResult?: any) => {
    // No-op placeholder: wallet-kit manages session/wallet state automatically.
    return;
  }, []);

  // Debug: log session and wallets whenever they change
  useEffect(() => {
    isDev &&
      console.log(
        "[LoginModal] useTurnkey session snapshot:",
        turnkey?.session,
      );
    if (turnkey?.wallets) {
      isDev &&
        console.log(
          "[LoginModal] useTurnkey wallets snapshot:",
          turnkey.wallets,
        );
    }
  }, [turnkey?.session, turnkey?.wallets]);

  // Identify user in PostHog whenever they log in (covers all auth methods)
  useEffect(() => {
    if (user?.id) {
      posthog.identify(user.id, {
        ...(user.email && { email: user.email }),
        ...(user.name && { username: user.name }),
      });
    }
  }, [user?.id, user?.email, user?.name]);

  // Track if we're in the middle of a login flow to prevent auto-close
  const isInNewUserFlowRef = useRef(false);

  useEffect(() => {
    if (open) {
      setShow(true);
      // Lock body scroll when modal is open to prevent interaction with background
      document.body.style.overflow = "hidden";

      // Check for token in cookies and refresh user if not already authenticated
      // BUT don't auto-close if we're in the username step (new user flow)
      const token = Cookies.get("token");

      // Don't do anything if we're in the username step or actively in new user flow
      if (loginStep === "username" || isInNewUserFlowRef.current) {
        return;
      }

      if (token && !user && !userLoading) {
        setLoading(true);
        refreshUser()
          .then(() => {
            setLoading(false);
            // Double-check we're not in username step before closing
            // Note: We don't auto-close here anymore - let login handlers manage closing
          })
          .catch(() => setLoading(false));
      }
    } else {
      // Unlock body scroll when modal closes
      document.body.style.overflow = "";
      // Clear all loading states when modal is closed
      clearAllLoadingStates();
      setSuccess(null);
      // Reset username step and flow ref
      setLoginStep("auth");
      setNewUsername("");
      setUsernameValidation({ isValid: false, isAvailable: null, error: null });
      isInNewUserFlowRef.current = false;

      const timeout = setTimeout(() => setShow(false), 220);
      return () => clearTimeout(timeout);
    }

    // Cleanup: ensure scroll is restored if component unmounts with modal open
    return () => {
      document.body.style.overflow = "";
    };
  }, [open, refreshUser, user, userLoading, onClose, loginStep]);

  useEffect(() => {
    if (!open) return;
    if (!turnkey) return;
    if (clientState !== ClientState.Ready) return;
    // Allow retry if nonce is missing; don't run again if we already have one
    if (googleNonce) return;

    (async () => {
      try {
        const pubKey = await turnkey.createApiKeyPair?.({
          storeOverride: false,
        });
        if (!pubKey) {
          throw new Error("Failed to create API keypair for Google login.");
        }
        pubKeyRef.current = pubKey;
        setGoogleNonce(bytesToHex(sha256(pubKey)));
      } catch (err: any) {
        console.error("Failed to prepare Google login", err);
        setError(err?.message || "Unable to prepare Google login.");
        // Leave googleNonce null so user can retry/reopen
      }
    })();
  }, [open, turnkey, clientState, googleNonce]);

  // Unified wallet login handler via wallet discovery
  // IMPORTANT: This useCallback must be ABOVE the early return to satisfy React's rules of hooks
  const handleWalletLogin = useCallback(
    (wallet: DiscoveredWallet) => {
      setError(null);
      setWalletError(null);
      setSuccess(null);

      connectAndSign(wallet, {
        onToken: async (token, isNewUser) => {
          isDev &&
            console.log("[LoginModal] Wallet login response:", {
              isNewUser,
              walletName: wallet.name,
            });

          if (isNewUser) {
            isInNewUserFlowRef.current = true;
          }

          await refreshUser();
          posthog.capture(isNewUser ? "wallet_connected" : "user_logged_in", {
            method: "wallet",
            wallet: wallet.name,
          });
          setSuccess(`${wallet.name} login successful`);
          recordAuthMethod("wallet");

          if (isNewUser) {
            isDev &&
              console.log(
                "[LoginModal] New user detected, showing username step",
              );
            setLoginStep("username");
            window.dispatchEvent(new CustomEvent("login-modal-keep-open"));
          } else {
            isDev && console.log("[LoginModal] Existing user, closing modal");
            onClose();
          }
        },
        onError: (msg) => {
          console.error("[LoginModal] Wallet login error:", msg);
          setWalletError(msg);
          toast.error(msg);
        },
        onUserLimitReached: (msg) => {
          setUserLimitReached(msg);
          setWalletError(null);
        },
      });
    },
    [connectAndSign, refreshUser, onClose, setUserLimitReached],
  );

  if (!open && !show) return null;

  // Login handler
  async function handleLoginEmail(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(null);
    try {
      const { token } = await apiLogin(email, password);
      Cookies.set("token", token, { expires: 7, path: "/" });
      await refreshUser();
      posthog.capture("user_logged_in", { method: "email" });
      setSuccess("Login successful!");

      setTimeout(() => {
        setSuccess(null);
        onClose();
      }, 1200);
    } catch (err: any) {
      setError(err.message || "Login failed");
    } finally {
      setLoading(false);
    }
  }

  // Registration handler
  async function handleRegister(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(null);
    try {
      const { user } = await apiRegister(email, username, password);
      if (user?.token) {
        Cookies.set("token", user.token, { expires: 7, path: "/" });
      }
      Cookies.set("username", username, { expires: 7, path: "/" });
      Cookies.set("email", email, { expires: 7, path: "/" });
      await refreshUser();
      posthog.capture("user_signed_up", { method: "email" });
      setSuccess("Registration successful!");
      setTimeout(() => {
        setMode("login");
        setSuccess(null);
      }, 1200);
    } catch (err: any) {
      // Check if this is a user limit error
      if (err instanceof ApiError && err.code === "USER_LIMIT_REACHED") {
        setUserLimitReached(err.message);
        setError(null); // Don't show error in modal, blocker will show
      } else {
        setError(err.message || "Registration failed");
      }
    } finally {
      setLoading(false);
    }
  }


  async function handleGoogleSuccess(resp: CredentialResponse) {
    setGoogleLoading(true);
    setError(null);
    setSuccess(null);

    try {
      const publicKey = pubKeyRef.current;
      if (!publicKey) {
        throw new Error("Google login is not ready yet. Please try again.");
      }

      if (!resp?.credential) {
        throw new Error("Google login did not return a credential.");
      }

      if (!turnkey?.completeOauth) {
        throw new Error("Turnkey OAuth is not available right now.");
      }

      // -------- Decode Google token ----------
      isDev && console.log("Google credential:", resp.credential);
      const decoded = (() => {
        try {
          const [, payloadSegment] = resp.credential.split(".");
          if (!payloadSegment) return {};

          const payloadJson = atob(
            payloadSegment.replace(/-/g, "+").replace(/_/g, "/"),
          );
          return JSON.parse(payloadJson);
        } catch {
          return {};
        }
      })();

      isDev && console.log("Decoded Google payload:", decoded);

      const email =
        typeof decoded?.email === "string" ? decoded.email : undefined;
      const name =
        typeof decoded?.name === "string"
          ? decoded.name
          : typeof decoded?.given_name === "string"
            ? decoded.given_name
            : undefined;

      // -------- Build minimal sub-org params ----------
      let createSubOrgParams: any = undefined;

      if (email || name) {
        const label = (email || name || "google-user")
          .toLowerCase()
          .replace(/\s+/g, "-");

        createSubOrgParams = {
          // REQUIRED:
          subOrgName: `narrative-${label}`,
          oauthProviders: [
            {
              providerName: "Google",
            },
          ],

          // OPTIONAL but recommended metadata:
          ...(name && { userName: name }),
          ...(email && { userEmail: email }),
        };
      }

      isDev && console.log("createSubOrgParams:", createSubOrgParams);

      // -------- Build OAuth params ----------
      const oauthParams: any = {
        oidcToken: resp.credential,
        publicKey,
        providerName: "Google",
        createSubOrgParams: {
          userName: name,
        },
      };

      isDev && console.log("Final OAuth params:", oauthParams);

      // -------- Complete OAuth login via Turnkey ----------
      const sessionResult = await turnkey.completeOauth(oauthParams);
      isDev && console.log("Turnkey OAuth result:", sessionResult);

      setSuccess("Google sign-in complete!");
      recordAuthMethod("google");
    } catch (err: any) {
      console.error("Turnkey Google OAuth failed:", err);

      const msg =
        err?.message ||
        err?.response?.data?.message ||
        "Google OAuth login failed";

      setError(msg);
      createdNonceRef.current = false;
      setGoogleNonce(null);
    } finally {
      setGoogleLoading(false);
    }
  }

  const handleGoogleError = () => {
    setGoogleLoading(false);
    setError("Google login was cancelled. Please try again.");
  };

  // Handle close attempt
  const handleClose = () => {
    if (forceLogin) {
      setWiggle(true);
      toast.error("Please log-in to trade on Interstate.");
      setTimeout(() => setWiggle(false), 600);
      return;
    }
    onClose();
  };

  return (
    <InterstatePopout
      open={open}
      onClose={handleClose}
      align="center"
      className={`relative max-h-[90vh] w-[440px] max-w-[94vw] overflow-y-auto rounded-2xl border border-white/[0.06] bg-[#060608] p-6 pt-10 text-zinc-100 shadow-[0_0_80px_rgba(0,0,0,0.8),0_0_120px_rgba(24,196,140,0.04)] ${wiggle ? "wiggle" : ""}`}
      disableClickOutside={forceLogin}
      zIndex={99999}
      overlayClassName="bg-black/80 backdrop-blur-sm"
    >
      {/* Subtle glow accents */}
      <div className="pointer-events-none absolute -top-32 -left-32 h-64 w-64 rounded-full bg-emerald-500/[0.03] blur-[100px]" />
      <div className="pointer-events-none absolute -right-20 -bottom-20 h-48 w-48 rounded-full bg-emerald-500/[0.02] blur-[80px]" />
      
      {/* Close button */}
      <button
        className="absolute top-4 right-4 flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.06] bg-white/[0.02] text-sm text-zinc-500 transition-all hover:border-white/[0.1] hover:bg-white/[0.05] hover:text-zinc-300"
        onClick={handleClose}
        type="button"
      >
        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M1 1L13 13M1 13L13 1" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
        </svg>
      </button>

      {/* Username Setup Step */}
      {loginStep === "username" ? (
        <div className="py-2">
          <div className="mb-8 text-center">
            <p className="text-[10px] font-medium tracking-[0.25em] text-emerald-400/80 uppercase">
              Welcome to Interstate
            </p>
            <h2 className="mt-3 text-xl font-medium tracking-tight text-white">
              Choose Your Username
            </h2>
            <p className="mt-2 text-[13px] leading-relaxed text-zinc-500">
              Pick a unique username for your profile
            </p>
          </div>

          <div className="mb-6">
            <label className="mb-2 block text-[11px] font-medium tracking-wide text-zinc-500 uppercase">
              Username
            </label>
            <div className="relative">
              <span className="absolute top-1/2 left-4 -translate-y-1/2 text-zinc-600">
                @
              </span>
              <input
                type="text"
                value={newUsername}
                onChange={(e) => handleNewUsernameChange(e.target.value)}
                placeholder="your_username"
                maxLength={20}
                className={`w-full rounded-lg border bg-white/[0.02] py-3 pr-12 pl-9 text-sm text-white placeholder-zinc-600 transition-all focus:outline-none ${
                  usernameValidation.error
                    ? "border-red-500/40 focus:border-red-500/60"
                    : usernameValidation.isAvailable
                      ? "border-emerald-500/40 focus:border-emerald-500/60"
                      : "border-white/[0.06] focus:border-emerald-500/40"
                }`}
              />
              <div className="absolute top-1/2 right-4 -translate-y-1/2">
                {usernameChecking ? (
                  <FiLoader className="h-4 w-4 animate-spin text-zinc-500" />
                ) : usernameValidation.isAvailable ? (
                  <FiCheck className="h-4 w-4 text-emerald-400" />
                ) : usernameValidation.error ? (
                  <FiAlertCircle className="h-4 w-4 text-red-400" />
                ) : null}
              </div>
            </div>

            {usernameValidation.error && (
              <p className="mt-2 text-[11px] text-red-400">
                {usernameValidation.error}
              </p>
            )}
            {usernameValidation.isAvailable && !usernameChecking && (
              <p className="mt-2 text-[11px] text-emerald-400">
                Username is available
              </p>
            )}

            <p className="mt-3 text-[11px] leading-relaxed text-zinc-600">
              3-20 characters. Letters, numbers, and underscores only.
            </p>
          </div>

          {/* Referral link preview */}
          {newUsername && usernameValidation.isValid && (
            <div className="mb-6 rounded-lg border border-emerald-500/20 bg-emerald-500/[0.04] p-3">
              <p className="mb-1.5 text-[10px] font-medium tracking-wide text-emerald-400/80 uppercase">
                Your referral link
              </p>
              <p className="font-mono text-xs break-all text-zinc-300">
                interstate.trade?ref=
                <span className="text-emerald-400">{newUsername.toLowerCase().substring(0, 10)}</span>
              </p>
            </div>
          )}

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => {
                window.dispatchEvent(new CustomEvent("login-modal-can-close"));
                onClose();
              }}
              className="flex-1 rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-2.5 text-sm font-medium text-zinc-400 transition-all hover:border-white/[0.1] hover:bg-white/[0.04] hover:text-zinc-300"
            >
              Skip for now
            </button>
            <button
              type="button"
              onClick={handleUsernameSubmit}
              disabled={
                !usernameValidation.isValid ||
                !usernameValidation.isAvailable ||
                usernameChecking ||
                usernameSubmitting
              }
              className={`flex-1 rounded-lg px-4 py-2.5 text-sm font-medium transition-all ${
                usernameValidation.isValid &&
                usernameValidation.isAvailable &&
                !usernameChecking &&
                !usernameSubmitting
                  ? "bg-emerald-500 text-white shadow-[0_0_20px_rgba(16,185,129,0.2)] hover:bg-emerald-400"
                  : "cursor-not-allowed bg-white/[0.04] text-zinc-600"
              }`}
            >
              {usernameSubmitting ? (
                <span className="flex items-center justify-center gap-2">
                  <FiLoader className="h-4 w-4 animate-spin" />
                  Saving...
                </span>
              ) : (
                "Continue"
              )}
            </button>
          </div>
        </div>
      ) : (
        <>
          {/* Auth Step */}
          <div className="mb-6 text-center">
            <p className="text-[10px] font-medium tracking-[0.25em] text-emerald-400/80 uppercase">
              Secure Access
            </p>
            <h2 className="mt-3 text-xl font-medium tracking-tight text-white">
              Sign in to Interstate
            </h2>
          </div>
          {error && (
            <div className="mb-4 rounded-lg border border-red-500/30 bg-red-500/[0.06] px-3 py-2.5 text-[12px] text-red-300">
              {error}
            </div>
          )}

          {ENABLE_EMAIL_AUTH && (
            <>
              {mode === "login" ? (
                <form onSubmit={handleLoginEmail}>
                  <div className="mb-3">
                    <label className="mb-1 block text-xs">Email</label>
                    <input
                      type="email"
                      className="mb-2 w-full rounded-3xl border border-neutral-700 px-3 py-2 text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                      placeholder="Enter email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required
                    />
                    <label className="mb-1 block text-xs">Password</label>
                    <input
                      type="password"
                      className="mb-2 w-full rounded-3xl border border-neutral-700 px-3 py-2 text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                      placeholder="Enter password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                    />
                    <div className="mb-2 flex justify-end">
                      <InterstateButton
                        variant="secondary"
                        size="sm"
                        type="button"
                        className="h-auto border-none bg-transparent px-0 py-0 text-xs text-emerald-400 shadow-none hover:underline"
                      >
                        Forgot password?
                      </InterstateButton>
                    </div>
                  </div>
                  {error && (
                    <div className="mb-2 text-center text-xs text-red-400">
                      {error}
                    </div>
                  )}
                  {success && (
                    <div className="mb-2 text-center text-xs text-emerald-400">
                      {success}
                    </div>
                  )}
                  <InterstateButton
                    type="submit"
                    fullWidth
                    loading={loading}
                    className="mb-3"
                  >
                    Login
                  </InterstateButton>
                </form>
              ) : (
                <form onSubmit={handleRegister}>
                  <div className="mb-4 text-center text-xl font-bold">
                    Sign Up
                  </div>
                  <div className="mb-3">
                    <label className="mb-1 block text-xs">Username</label>
                    <input
                      type="text"
                      className="mb-2 w-full rounded-3xl border border-neutral-700 px-3 py-2 text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                      placeholder="Enter username"
                      value={username}
                      onChange={(e) => setUsername(e.target.value)}
                      required
                    />
                    <label className="mb-1 block text-xs">Email</label>
                    <input
                      type="email"
                      className="mb-2 w-full rounded-3xl border border-neutral-700 px-3 py-2 text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                      placeholder="Enter email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                      required
                    />
                    <label className="mb-1 block text-xs">Password</label>
                    <input
                      type="password"
                      className="mb-2 w-full rounded-3xl border border-neutral-700 px-3 py-2 text-xs focus:ring-2 focus:ring-emerald-500 focus:outline-none"
                      placeholder="Enter password"
                      value={password}
                      onChange={(e) => setPassword(e.target.value)}
                      required
                    />
                  </div>
                  {error && (
                    <div className="mb-2 text-center text-xs text-red-400">
                      {error}
                    </div>
                  )}
                  {success && (
                    <div className="mb-2 text-center text-xs text-emerald-400">
                      {success}
                    </div>
                  )}
                  <InterstateButton
                    type="submit"
                    fullWidth
                    loading={loading}
                    className="mb-3"
                  >
                    Sign Up
                  </InterstateButton>
                  <div className="mt-3 text-center text-xs text-neutral-400">
                    Already have an account?{" "}
                    <button
                      className="h-auto border-none bg-transparent px-0 py-0 text-emerald-400 shadow-none hover:underline"
                      onClick={() => setMode("login")}
                    >
                      Login
                    </button>
                  </div>
                  <div className="mt-4 text-center text-xs text-neutral-500">
                    By creating an account, you agree to Interstate's{" "}
                    <a href="#" className="underline">
                      Privacy Policy
                    </a>{" "}
                    and{" "}
                    <a href="#" className="underline">
                      Terms of Service
                    </a>
                    .
                  </div>
                </form>
              )}
            </>
          )}
          {/* Divider */}
          <div className="relative my-5">
            <div className="absolute inset-0 flex items-center">
              <div className="w-full border-t border-white/[0.06]"></div>
            </div>
          </div>
          
          <div className="flex flex-col items-center gap-3">
            {googleClientId ? (
              <GoogleOAuthProvider clientId={googleClientId}>
                <div
                  className={`flex flex-col items-center ${AUTH_BUTTON_WIDTH_CLASS}`}
                >
                  {authState === AuthState.Authenticated ? (
                    <div className="w-full rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-center text-[13px] text-zinc-400">
                      Finishing sign-in…
                    </div>
                  ) : clientState !== ClientState.Ready ? (
                    <div className="w-full rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-center text-[13px] text-zinc-500">
                      Preparing login…
                    </div>
                  ) : !googleNonce ? (
                    <div className="w-full rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-center text-[13px] text-zinc-500">
                      {googleLoading ? "Finishing sign-in…" : "Preparing…"}
                    </div>
                  ) : googleLoading ? (
                    <div className="w-full rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-center text-[13px] text-zinc-400">
                      Signing in with Google…
                    </div>
                  ) : (
                    <div className="flex w-full justify-center">
                      <GoogleLogin
                        nonce={googleNonce}
                        onSuccess={handleGoogleSuccess}
                        onError={handleGoogleError}
                        useOneTap={false}
                        theme="filled_black"
                        shape="rectangular"
                        text="continue_with"
                        size="large"
                        width="400"
                      />
                    </div>
                  )}
                </div>
              </GoogleOAuthProvider>
            ) : (
              <div className={`w-full rounded-lg border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-center text-[13px] text-zinc-600 ${AUTH_BUTTON_WIDTH_CLASS}`}>
                Google login not configured
              </div>
            )}
          </div>

          {(walletError || discoveryWalletError) && (
            <div className="mt-4 text-center text-[12px] text-red-400">
              {walletError || discoveryWalletError}
            </div>
          )}

          {/* Wallet list */}
          {allWallets.length > 0 && (
            <div className={`mt-5 ${AUTH_BUTTON_WIDTH_CLASS}`}>
              <div className="mb-3 text-[10px] font-medium tracking-[0.2em] text-zinc-600 uppercase">
                Or continue with wallet
              </div>
              <div className="max-h-[32vh] space-y-2 overflow-y-auto">
                {allWallets.map((w) => (
                  <button
                    key={w.id}
                    type="button"
                    className={`group flex w-full items-center gap-3 rounded-lg border border-white/[0.06] bg-white/[0.02] p-3 transition-all hover:border-white/[0.1] hover:bg-white/[0.04] ${activeWalletId === w.id ? "cursor-wait border-emerald-500/30 bg-emerald-500/[0.04]" : ""} ${activeWalletId && activeWalletId !== w.id ? "pointer-events-none opacity-30" : ""}`}
                    onClick={() => {
                      setGoogleLoading(false);
                      handleWalletLogin(w);
                    }}
                    disabled={!!activeWalletId}
                  >
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-white/[0.04]">
                      <img
                        src={w.icon}
                        alt=""
                        className="h-5 w-5 shrink-0"
                        onError={(e) => {
                          (e.target as HTMLImageElement).style.display = "none";
                        }}
                      />
                    </div>
                    <span className="text-[13px] font-medium text-zinc-300 transition-colors group-hover:text-white">{w.name}</span>
                    {activeWalletId === w.id && (
                      <span className="ml-auto text-[11px] font-medium text-emerald-400">
                        Connecting...
                      </span>
                    )}
                  </button>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </InterstatePopout>
  );
}
