import React, { useCallback, useEffect, useRef, useState } from 'react';
import { login as apiLogin, register as apiRegister, checkUsernameAvailability, updateUsername } from '../utils/api';
import Cookies from 'js-cookie';
import { useUser } from "./UserContext";
import InterstatePopout from './InterstatePopout';
import InterstateButton from './InterstateButton';
import { toast } from 'react-hot-toast';
import { useTurnkey, ClientState, AuthState } from '@turnkey/react-wallet-kit';
import { GoogleOAuthProvider, GoogleLogin, type CredentialResponse } from '@react-oauth/google';
import { sha256 } from '@noble/hashes/sha256';
import { bytesToHex } from '@noble/hashes/utils';
import bs58 from "bs58";
import { clearStoredReferralCodeHint, getStoredReferralCodeHint } from "../utils/referralStorage";
import { useUserLimit } from "./UserLimitContext";
import { ApiError } from "../utils/api";
import { FiCheck, FiAlertCircle, FiLoader } from 'react-icons/fi';

const isDev = process.env.NODE_ENV !== 'production';
const ENABLE_EMAIL_AUTH = false;
const AUTH_BUTTON_WIDTH_CLASS = 'w-full max-w-[400px] mx-auto';
const SESSION_METADATA_KEY = "@turnkey/session-metadata";

interface LoginModalProps {
  open: boolean;
  onClose: () => void;
  forceLogin?: boolean;
}

// Extend the Window interface to include the solana property
declare global {
  interface Window {
    solana?: any;
    ethereum?: any;
  }
}

const TURNKEY_AUTH_METHOD_EVENT = "turnkey-auth-method";
const TURNKEY_APIKEY_READY_EVENT = "turnkey-apikey-ready";
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;

const recordAuthMethod = (method: "google" | "wallet") => {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("turnkeyLastAuthMethod", method);
    window.dispatchEvent(new CustomEvent(TURNKEY_AUTH_METHOD_EVENT, { detail: method }));
  } catch (err) {
    console.warn("[LoginModal] Failed to persist auth method", err);
  }
};

const recordPasskeyReady = () => {
  if (typeof window === "undefined") return;
  try {
    window.localStorage.setItem("turnkeyPasskeyReady", "true");
    window.dispatchEvent(new CustomEvent("turnkey-passkey-ready"));
  } catch (err) {
    console.warn("[LoginModal] Failed to persist passkey ready flag", err);
  }
};

const buildWalletLoginMessage = () =>
  `Login to Interstate with nonce: ${Date.now()}`;

export default function LoginModal({ open, onClose, forceLogin = false }: LoginModalProps) {
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [email, setEmail] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [show, setShow] = useState(false);
  
  // Separate loading states for each login method
  const [loading, setLoading] = useState(false); // For email/password login
  const [phantomLoading, setPhantomLoading] = useState(false);
  const [metamaskLoading, setMetamaskLoading] = useState(false);
  const [googleLoading, setGoogleLoading] = useState(false);
  const [googleNonce, setGoogleNonce] = useState<string | null>(null);
  const pubKeyRef = useRef<string | null>(null);
  const createdNonceRef = useRef(false);
  const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
  
  const [error, setError] = useState<string | null>(null);
  const [walletError, setWalletError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const { refreshUser, user, loading: userLoading } = useUser();
  const { setUserLimitReached } = useUserLimit();
  const [wiggle, setWiggle] = useState(false);
  const [showWalletOptions, setShowWalletOptions] = useState(false);

  // Username setup step for new users
  const [loginStep, setLoginStep] = useState<'auth' | 'username'>('auth');
  const [newUsername, setNewUsername] = useState('');
  const [usernameChecking, setUsernameChecking] = useState(false);
  const [usernameSubmitting, setUsernameSubmitting] = useState(false);
  const [usernameValidation, setUsernameValidation] = useState<{
    isValid: boolean;
    isAvailable: boolean | null;
    error: string | null;
  }>({ isValid: false, isAvailable: null, error: null });
  const usernameCheckTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  
  // Use Turnkey SDK for wallet authentication
const turnkey = useTurnkey();
const authState = turnkey?.authState;
const clientState = turnkey?.clientState;
  // Helper function to clear all loading states
  const clearAllLoadingStates = () => {
    setPhantomLoading(false);
    setMetamaskLoading(false);
    setGoogleLoading(false);
    setError(null);
    setWalletError(null);
  };

  // Check if username looks auto-generated (wallet address or similar)
  const isAutoGeneratedUsername = (name: string | null | undefined): boolean => {
    if (!name) return true;
    // Check if it looks like a wallet address (hex or base58)
    if (/^(0x)?[a-fA-F0-9]{40,}$/.test(name)) return true;
    if (/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(name)) return true;
    // Check if it starts with "user_" (auto-generated pattern)
    if (/^user_[a-z0-9]+$/i.test(name)) return true;
    return false;
  };

  // Username format validation
  const validateUsernameFormat = (value: string): { valid: boolean; error: string | null } => {
    if (!value || value.length === 0) {
      return { valid: false, error: null };
    }
    if (value.length < 3) {
      return { valid: false, error: 'Username must be at least 3 characters' };
    }
    if (value.length > 20) {
      return { valid: false, error: 'Username must be 20 characters or less' };
    }
    const usernameRegex = /^[a-zA-Z_][a-zA-Z0-9_]*$/;
    if (!usernameRegex.test(value)) {
      if (!/^[a-zA-Z_]/.test(value)) {
        return { valid: false, error: 'Username must start with a letter or underscore' };
      }
      return { valid: false, error: 'Only letters, numbers, and underscores allowed' };
    }
    const reservedWords = ['admin', 'administrator', 'root', 'system', 'interstate', 'support', 'help', 'null', 'undefined'];
    if (reservedWords.includes(value.toLowerCase())) {
      return { valid: false, error: 'This username is reserved' };
    }
    return { valid: true, error: null };
  };

  // Handle username input change with debounced availability check
  const handleNewUsernameChange = (value: string) => {
    // Allow uppercase letters - only strip invalid characters
    const cleanValue = value.replace(/[^a-zA-Z0-9_]/g, '');
    setNewUsername(cleanValue);

    // Clear previous timeout
    if (usernameCheckTimeoutRef.current) {
      clearTimeout(usernameCheckTimeoutRef.current);
    }

    // Validate format first
    const formatValidation = validateUsernameFormat(cleanValue);
    if (!formatValidation.valid) {
      setUsernameValidation({
        isValid: false,
        isAvailable: null,
        error: formatValidation.error,
      });
      return;
    }

    // Debounce availability check
    setUsernameChecking(true);
    usernameCheckTimeoutRef.current = setTimeout(async () => {
      try {
        const result = await checkUsernameAvailability(cleanValue);
        setUsernameValidation({
          isValid: result.valid,
          isAvailable: result.available,
          error: result.available ? null : 'Username is already taken',
        });
      } catch (err: any) {
        setUsernameValidation({
          isValid: false,
          isAvailable: false,
          error: err?.message || 'Failed to check availability',
        });
      } finally {
        setUsernameChecking(false);
      }
    }, 500);
  };

  // Handle username submission
  const handleUsernameSubmit = async () => {
    if (!usernameValidation.isValid || !usernameValidation.isAvailable || !user?.bearerToken) {
      return;
    }

    setUsernameSubmitting(true);
    try {
      const result = await updateUsername(user.bearerToken, newUsername);
      if (result.success) {
        await refreshUser();
        toast.success('Username set successfully!');
        // Clear the new user flow ref and signal parent can close
        isInNewUserFlowRef.current = false;
        window.dispatchEvent(new CustomEvent('login-modal-can-close'));
        onClose();
      }
    } catch (err: any) {
      toast.error(err?.message || 'Failed to set username');
    } finally {
      setUsernameSubmitting(false);
    }
  };

  // Handle successful login - check if username needs to be set
  const handleSuccessfulLogin = async (isNewUser: boolean = false) => {
    await refreshUser();
    // Give time for user context to update
    setTimeout(() => {
      // Check if user has an auto-generated username
      const currentUser = Cookies.get('token') ? user : null;
      if (isNewUser || isAutoGeneratedUsername(currentUser?.name)) {
        setLoginStep('username');
      } else {
        onClose();
      }
    }, 100);
  };

  // After wallet login, optionally fetch wallets once to populate SDK state (after ensuring session)
  // Accepts optional loginResult to use its session data directly (more reliable than turnkey.session)
  const finalizeWalletLoginSession = useCallback(async (_loginResult?: any) => {
    // No-op placeholder: wallet-kit manages session/wallet state automatically.
    return;
  }, []);

  // Debug: log session and wallets whenever they change
  useEffect(() => {
    isDev && console.log("[LoginModal] useTurnkey session snapshot:", turnkey?.session);
    if (turnkey?.wallets) {
      isDev && console.log("[LoginModal] useTurnkey wallets snapshot:", turnkey.wallets);
    }
  }, [turnkey?.session, turnkey?.wallets]);


  // Track if we're in the middle of a login flow to prevent auto-close
  const isInNewUserFlowRef = useRef(false);

  useEffect(() => {
    if (open) {
      setShow(true);
      // Lock body scroll when modal is open to prevent interaction with background
      document.body.style.overflow = 'hidden';

      // Check for token in cookies and refresh user if not already authenticated
      // BUT don't auto-close if we're in the username step (new user flow)
      const token = Cookies.get('token');

      // Don't do anything if we're in the username step or actively in new user flow
      if (loginStep === 'username' || isInNewUserFlowRef.current) {
        return;
      }

      if (token && !user && !userLoading) {
        setLoading(true);
        refreshUser().then(() => {
          setLoading(false);
          // Double-check we're not in username step before closing
          // Note: We don't auto-close here anymore - let login handlers manage closing
        }).catch(() => setLoading(false));
      }
    } else {
      // Unlock body scroll when modal closes
      document.body.style.overflow = '';
      // Clear all loading states when modal is closed
      clearAllLoadingStates();
      setSuccess(null);
      // Reset username step and flow ref
      setLoginStep('auth');
      setNewUsername('');
      setUsernameValidation({ isValid: false, isAvailable: null, error: null });
      isInNewUserFlowRef.current = false;

      const timeout = setTimeout(() => setShow(false), 220);
      return () => clearTimeout(timeout);
    }

    // Cleanup: ensure scroll is restored if component unmounts with modal open
    return () => {
      document.body.style.overflow = '';
    };
  }, [open, refreshUser, user, userLoading, onClose, loginStep]);

  useEffect(() => {
    if (!open) return;
    if (!turnkey) return;
    if (clientState !== ClientState.Ready) return;
    // Allow retry if nonce is missing; don't run again if we already have one
    if (googleNonce) return;

    (async () => {
      try {
        const pubKey = await turnkey.createApiKeyPair?.({ storeOverride: false });
        if (!pubKey) {
          throw new Error("Failed to create API keypair for Google login.");
        }
        pubKeyRef.current = pubKey;
        setGoogleNonce(bytesToHex(sha256(pubKey)));
      } catch (err: any) {
        console.error("Failed to prepare Google login", err);
        setError(err?.message || "Unable to prepare Google login.");
        // Leave googleNonce null so user can retry/reopen
      }
    })();
  }, [open, turnkey, clientState, googleNonce]);

  if (!open && !show) return null;

  // Login handler
  async function handleLoginEmail(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(null);
    try {
      const { token } = await apiLogin(email, password);
      Cookies.set('token', token, { expires: 7, path: '/' });
      await refreshUser();
      setSuccess('Login successful!');

      setTimeout(() => {
        setSuccess(null);
        onClose();
      }, 1200);
    } catch (err: any) {
      setError(err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  }

  // Registration handler
  async function handleRegister(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    setSuccess(null);
    try {
      const { user } = await apiRegister(email, username, password);
      if (user?.token) {
        Cookies.set('token', user.token, { expires: 7, path: '/' });
      }
      Cookies.set('username', username, { expires: 7, path: '/' });
      Cookies.set('email', email, { expires: 7, path: '/' });
      await refreshUser();
      setSuccess('Registration successful!');
      setTimeout(() => {
        setMode('login');
        setSuccess(null);
      }, 1200);
    } catch (err: any) {
      // Check if this is a user limit error
      if (err instanceof ApiError && err.code === 'USER_LIMIT_REACHED') {
        setUserLimitReached(err.message);
        setError(null); // Don't show error in modal, blocker will show
      } else {
        setError(err.message || 'Registration failed');
      }
    } finally {
      setLoading(false);
    }
  }



//   async function handleGoogleSuccess(resp: CredentialResponse) {
//   setGoogleLoading(true);
//   setError(null);
//   setSuccess(null);

//   try {
//     const publicKey = pubKeyRef.current;
//     if (!publicKey) {
//       throw new Error("Google login is not ready yet. Please try again.");
//     }

//     if (!resp?.credential) {
//       throw new Error("Google login did not return a credential.");
//     }

//     if (!turnkey?.completeOauth) {
//       throw new Error("Turnkey OAuth is not available right now.");
//     }

//     // -------- Decode Google ID token to extract optional metadata ----------
//     isDev && console.log("Google credential:", resp.credential);
//     const createSubOrgParams = (() => {
//       try {
//         const [, payloadSegment] = resp.credential.split(".");
//         if (!payloadSegment) return undefined;

//         const payloadJson = atob(
//           payloadSegment.replace(/-/g, "+").replace(/_/g, "/")
//         );
//         const payload = JSON.parse(payloadJson);
//         console.log("Decoded Google token payload:", payload);
//         const email =
//           typeof payload?.email === "string" ? payload.email : undefined;
//         const name =
//           typeof payload?.name === "string"
//             ? payload.name
//             : typeof payload?.given_name === "string"
//             ? payload.given_name
//             : undefined;

//         if (!email && !name) return undefined;

//         return {
//           ...(name && { userName: name }),
//           ...(email && { userEmail: email }),
//         };
//       } catch (err) {
//         console.warn("Could not decode Google token for signup metadata", err);
//         return undefined;
//       }
//     })();

//     isDev && console.log("createSubOrgParams:", createSubOrgParams);

//     // -------- Build OAuth parameters for Turnkey --------
//     const oauthParams: any = {
//       oidcToken: resp.credential,
//       publicKey,
//       providerName: "Google"
//     };
//     console.log("OAuth params before sub-org:", oauthParams);
//     if (createSubOrgParams) {
//     oauthParams.createSubOrgParams = createSubOrgParams;
//     }
//     isDev && console.log("Final OAuth params:", oauthParams);

//     // -------- SUPER IMPORTANT: Use completeWithOauth --------
//     const sessionResult = await turnkey.completeOauth(oauthParams);

//     isDev && console.log("Turnkey OAuth result:", sessionResult);
//     setSuccess("Google sign-in complete!");

//   } catch (err: any) {
//     console.error("Turnkey Google OAuth failed:", err);

//     const message =
//       err?.message ||
//       err?.response?.data?.message ||
//       "Google OAuth login failed";

//     setError(message);
//     createdNonceRef.current = false;
//     setGoogleNonce(null);

//   } finally {
//     setGoogleLoading(false);
//   }
// }

async function handleGoogleSuccess(resp: CredentialResponse) {
  setGoogleLoading(true);
  setError(null);
  setSuccess(null);

  try {
    const publicKey = pubKeyRef.current;
    if (!publicKey) {
      throw new Error("Google login is not ready yet. Please try again.");
    }

    if (!resp?.credential) {
      throw new Error("Google login did not return a credential.");
    }

    if (!turnkey?.completeOauth) {
      throw new Error("Turnkey OAuth is not available right now.");
    }

    // -------- Decode Google token ----------
    isDev && console.log("Google credential:", resp.credential);
    const decoded = (() => {
      try {
        const [, payloadSegment] = resp.credential.split(".");
        if (!payloadSegment) return {};

        const payloadJson = atob(
          payloadSegment.replace(/-/g, "+").replace(/_/g, "/")
        );
        return JSON.parse(payloadJson);
      } catch {
        return {};
      }
    })();

    isDev && console.log("Decoded Google payload:", decoded);

    const email =
      typeof decoded?.email === "string" ? decoded.email : undefined;
    const name =
      typeof decoded?.name === "string"
        ? decoded.name
        : typeof decoded?.given_name === "string"
        ? decoded.given_name
        : undefined;

    // -------- Build minimal sub-org params ----------
    let createSubOrgParams: any = undefined;

    if (email || name) {
      const label = (email || name || "google-user")
        .toLowerCase()
        .replace(/\s+/g, "-");

      createSubOrgParams = {
        // REQUIRED:
        subOrgName: `narrative-${label}`,
        oauthProviders: [
          {
            providerName: "Google",
          },
        ],

        // OPTIONAL but recommended metadata:
        ...(name && { userName: name }),
        ...(email && { userEmail: email }),
      };
    }

    isDev && console.log("createSubOrgParams:", createSubOrgParams);

    // -------- Build OAuth params ----------
    const oauthParams: any = {
      oidcToken: resp.credential,
      publicKey,
      providerName: "Google",
      createSubOrgParams : {
        userName: name
      }
    };



    isDev && console.log("Final OAuth params:", oauthParams);

    // -------- Complete OAuth login via Turnkey ----------
    const sessionResult = await turnkey.completeOauth(oauthParams);
    isDev && console.log("Turnkey OAuth result:", sessionResult);

    setSuccess("Google sign-in complete!");
    recordAuthMethod("google");

  } catch (err: any) {
    console.error("Turnkey Google OAuth failed:", err);

    const msg =
      err?.message ||
      err?.response?.data?.message ||
      "Google OAuth login failed";

    setError(msg);
    createdNonceRef.current = false;
    setGoogleNonce(null);
  } finally {
    setGoogleLoading(false);
  }
}

  const handleGoogleError = () => {
    setGoogleLoading(false);
    setError('Google login was cancelled. Please try again.');
  };


  // Phantom Wallet Login handler - server-side Turnkey wallet + backend JWT
  async function handlePhantomLogin() {
    setPhantomLoading(true);
    setError(null);
    setWalletError(null);
    setSuccess(null);

    try {
      if (!BACKEND_URL) {
        throw new Error("Backend URL is not configured");
      }

      const provider = (window as any).solana;
      if (!provider) {
        setWalletError('Phantom wallet not found. Please install Phantom wallet and refresh the page.');
        return;
      }

      const connectionResult = await provider.connect?.();
      const publicKey =
        connectionResult?.publicKey?.toString?.() ||
        provider.publicKey?.toString?.();

      if (!publicKey) {
        setWalletError('Unable to read Phantom public key. Please try again.');
        return;
      }

      const message = buildWalletLoginMessage();
      const encodedMessage = new TextEncoder().encode(message);
      const signed = await provider.signMessage(encodedMessage, "utf8");
      const signatureBytes = signed?.signature || signed;
      const signatureBase58 = bs58.encode(signatureBytes);

      const referralCode = getStoredReferralCodeHint() || undefined;

      const response = await fetch(`${BACKEND_URL}/api/users/phantom/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          publicKey,
          signature: signatureBase58,
          message,
          referralCode,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        // Check for user limit error
        if (data?.code === 'USER_LIMIT_REACHED') {
          setUserLimitReached(data?.message);
          setWalletError(null);
          return;
        }
        const errorMsg = data?.error || `Phantom login failed (${response.status})`;
        throw new Error(errorMsg);
      }

      const token = data?.token;
      if (!token) {
        throw new Error("Login succeeded but no token was returned.");
      }

      Cookies.set("token", token, { expires: 7, path: "/" });
      clearStoredReferralCodeHint();

      // Check if this is a new user (backend returns isNewUser flag)
      const isNewUser = data?.isNewUser === true;
      isDev && console.log("[LoginModal] Phantom login response:", { isNewUser, data });

      // If new user, set the ref BEFORE refreshUser to prevent useEffect from interfering
      if (isNewUser) {
        isInNewUserFlowRef.current = true;
      }

      await refreshUser();
      setSuccess("Phantom login successful");
      recordAuthMethod("wallet");

      // If new user, show username step; otherwise close
      if (isNewUser) {
        isDev && console.log("[LoginModal] New user detected, showing username step");
        setLoginStep('username');
        // Dispatch event to tell parent NOT to auto-close the modal
        window.dispatchEvent(new CustomEvent('login-modal-keep-open'));
      } else {
        isDev && console.log("[LoginModal] Existing user, closing modal");
        onClose();
      }
    } catch (error: any) {
      console.error("[LoginModal] Phantom login error:", error);
      const msg = error?.message || "Phantom login failed. Please try again.";
      setWalletError(msg);
      toast.error(msg);
    } finally {
      setPhantomLoading(false);
    }
  }

  // MetaMask Wallet Login handler - server-side Turnkey wallet + backend JWT
  async function handleMetamaskLogin() {
    setMetamaskLoading(true);
    setError(null);
    setWalletError(null);
    setSuccess(null);

    try {
      if (!BACKEND_URL) {
        throw new Error("Backend URL is not configured");
      }

      const rawProvider = (window as any).ethereum;
      let ethereum = null;

      if (rawProvider?.providers && Array.isArray(rawProvider.providers)) {
        // Multiple wallets installed — find MetaMask specifically
        ethereum = rawProvider.providers.find((p: any) => p.isMetaMask === true);
      } else if (rawProvider?.isMetaMask === true) {
        // Single provider that is MetaMask
        ethereum = rawProvider;
      }

      if (!ethereum) {
        setWalletError('MetaMask wallet not found. Please install MetaMask extension.');
        return;
      }

      const accounts: string[] = await ethereum.request({
        method: "eth_requestAccounts",
      });
      const address = accounts?.[0];
      if (!address) {
        setWalletError("Unable to read MetaMask address. Please try again.");
        return;
      }

      const message = buildWalletLoginMessage();
      const signature = await ethereum.request({
        method: "personal_sign",
        params: [message, address],
      });

      const referralCode = getStoredReferralCodeHint() || undefined;

      const response = await fetch(`${BACKEND_URL}/api/users/metamask/login`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          address,
          signature,
          message,
          referralCode,
        }),
      });

      const data = await response.json().catch(() => ({}));
      if (!response.ok) {
        // Check for user limit error
        if (data?.code === 'USER_LIMIT_REACHED') {
          setUserLimitReached(data?.message);
          setWalletError(null);
          return;
        }
        const errorMsg = data?.error || `MetaMask login failed (${response.status})`;
        throw new Error(errorMsg);
      }

      const token = data?.token;
      if (!token) {
        throw new Error("Login succeeded but no token was returned.");
      }

      Cookies.set("token", token, { expires: 7, path: "/" });
      clearStoredReferralCodeHint();

      // Check if this is a new user (backend returns isNewUser flag)
      const isNewUser = data?.isNewUser === true;
      isDev && console.log("[LoginModal] MetaMask login response:", { isNewUser, data });

      // If new user, set the ref BEFORE refreshUser to prevent useEffect from interfering
      if (isNewUser) {
        isInNewUserFlowRef.current = true;
      }

      await refreshUser();
      setSuccess("MetaMask login successful");
      recordAuthMethod("wallet");

      // If new user, show username step; otherwise close
      if (isNewUser) {
        isDev && console.log("[LoginModal] New user detected, showing username step");
        setLoginStep('username');
        // Dispatch event to tell parent NOT to auto-close the modal
        window.dispatchEvent(new CustomEvent('login-modal-keep-open'));
      } else {
        isDev && console.log("[LoginModal] Existing user, closing modal");
        onClose();
      }
    } catch (error: any) {
      console.error("[LoginModal] MetaMask login error:", error);
      const msg = error?.message || "MetaMask login failed. Please try again.";
      setWalletError(msg);
      toast.error(msg);
    } finally {
      setMetamaskLoading(false);
    }
  }

  // Handle close attempt
  const handleClose = () => {
    if (forceLogin) {
      setWiggle(true);
      toast.error('Please log-in to trade on Interstate.');
      setTimeout(() => setWiggle(false), 600);
      return;
    }
    onClose();
  };

  return (
    <InterstatePopout
      open={open}
      onClose={handleClose}
      align="center"
      className={`relative w-[460px] max-w-[94vw] overflow-hidden rounded-[28px] border border-white/5 bg-[#0c0f18]/95 p-8 pt-12 shadow-[0_48px_160px_rgba(12,20,33,0.6)] backdrop-blur-xl text-neutral-100 ${wiggle ? ' wiggle' : ''}`}
      disableClickOutside={forceLogin}
      zIndex={150}
      overlayClassName="bg-[radial-gradient(circle_at_22%_18%,rgba(16,185,129,0.02),transparent_62%),radial-gradient(circle_at_78%_20%,rgba(59,130,246,0.02),transparent_58%),radial-gradient(circle_at_center,rgba(12,18,32,0.05),rgba(6,8,12,0.08))] !backdrop-blur-[2px]"
    >
      <div className="pointer-events-none absolute -inset-14 -z-10 bg-[radial-gradient(circle_at_top_left,rgba(16,185,129,0.25),transparent_55%),radial-gradient(circle_at_bottom_right,rgba(110,231,183,0.12),transparent_55%),radial-gradient(circle_at_top_right,rgba(129,140,248,0.2),transparent_55%)] opacity-80 blur-[90px]" />
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_center,rgba(148,163,184,0.12),transparent_70%)]" />
      <button
        className="absolute right-4 top-4 rounded-full bg-white/5 px-2 text-lg text-neutral-400 transition hover:bg-white/10 hover:text-white"
        onClick={handleClose}
        type="button"
      >
        ×
      </button>

      {/* Username Setup Step */}
      {loginStep === 'username' ? (
        <div className="py-2">
          <div className="mb-6 text-center">
            <p className="text-[0.65rem] uppercase tracking-[0.45em] text-emerald-300/70">
              Welcome to Interstate
            </p>
            <h2 className="mt-2 text-2xl font-semibold text-white">Choose Your Username</h2>
            <p className="mt-2 text-sm text-neutral-400">
              Pick a unique username for your profile and referral link
            </p>
          </div>

          <div className="mb-6">
            <label className="block text-xs font-medium text-neutral-400 mb-2">
              Username
            </label>
            <div className="relative">
              <span className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-500">
                @
              </span>
              <input
                type="text"
                value={newUsername}
                onChange={(e) => handleNewUsernameChange(e.target.value)}
                placeholder="your_username"
                maxLength={20}
                className={`w-full pl-8 pr-12 py-3 bg-neutral-800/50 border rounded-xl text-white placeholder-neutral-500 focus:outline-none focus:ring-2 transition-all ${
                  usernameValidation.error
                    ? 'border-red-500/50 focus:ring-red-500/30'
                    : usernameValidation.isAvailable
                    ? 'border-emerald-500/50 focus:ring-emerald-500/30'
                    : 'border-neutral-700 focus:ring-emerald-500/30'
                }`}
              />
              <div className="absolute right-4 top-1/2 -translate-y-1/2">
                {usernameChecking ? (
                  <FiLoader className="w-5 h-5 text-neutral-400 animate-spin" />
                ) : usernameValidation.isAvailable ? (
                  <FiCheck className="w-5 h-5 text-emerald-400" />
                ) : usernameValidation.error ? (
                  <FiAlertCircle className="w-5 h-5 text-red-400" />
                ) : null}
              </div>
            </div>

            {usernameValidation.error && (
              <p className="mt-2 text-xs text-red-400">{usernameValidation.error}</p>
            )}
            {usernameValidation.isAvailable && !usernameChecking && (
              <p className="mt-2 text-xs text-emerald-400">Username is available!</p>
            )}

            <p className="mt-3 text-xs text-neutral-500">
              3-20 characters. Letters, numbers, and underscores only. Must start with a letter or underscore.
            </p>
          </div>

          {/* Referral link preview */}
          {newUsername && usernameValidation.isValid && (
            <div className="mb-6 p-3 bg-emerald-900/20 rounded-xl border border-emerald-500/20">
              <p className="text-xs text-emerald-400 mb-1">Your referral link</p>
              <p className="text-white font-mono text-sm break-all">
                interstate.trade?ref={newUsername.toLowerCase().substring(0, 10)}
              </p>
            </div>
          )}

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => {
                // Signal parent that modal can close, then close
                window.dispatchEvent(new CustomEvent('login-modal-can-close'));
                onClose();
              }}
              className="flex-1 py-3 px-4 bg-neutral-800 hover:bg-neutral-700 text-white font-medium rounded-xl transition-colors"
            >
              Skip for now
            </button>
            <button
              type="button"
              onClick={handleUsernameSubmit}
              disabled={!usernameValidation.isValid || !usernameValidation.isAvailable || usernameChecking || usernameSubmitting}
              className={`flex-1 py-3 px-4 font-medium rounded-xl transition-all ${
                usernameValidation.isValid && usernameValidation.isAvailable && !usernameChecking && !usernameSubmitting
                  ? 'bg-emerald-600 hover:bg-emerald-500 text-white'
                  : 'bg-neutral-800 text-neutral-500 cursor-not-allowed'
              }`}
            >
              {usernameSubmitting ? (
                <span className="flex items-center justify-center gap-2">
                  <FiLoader className="w-4 h-4 animate-spin" />
                  Saving...
                </span>
              ) : (
                'Continue'
              )}
            </button>
          </div>
        </div>
      ) : (
        <>
          {/* Auth Step */}
          <div className="mb-4 text-center">
            <p className="text-[0.65rem] uppercase tracking-[0.45em] text-emerald-300/70">
              Secure Access
            </p>
            <h2 className="mt-2 text-2xl font-semibold text-white">Sign in to Interstate</h2>
          </div>
          {error && (
            <div className="mb-3 rounded-lg border border-red-500/40 bg-red-500/10 px-3 py-2 text-xs text-red-200">
              {error}
            </div>
          )}

      {ENABLE_EMAIL_AUTH && (
        <>
        {mode === 'login' ? (
          <form onSubmit={handleLoginEmail}>
            <div className="mb-3">
              <label className="block text-xs mb-1">Email</label>
              <input
                type="email"
                className="w-full px-3 py-2 rounded-3xl border border-neutral-700 text-xs mb-2 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="Enter email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                required
              />
              <label className="block text-xs mb-1">Password</label>
              <input
                type="password"
                className="w-full px-3 py-2 rounded-3xl border border-neutral-700 text-xs mb-2 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="Enter password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                required
              />
              <div className="flex justify-end mb-2">
                <InterstateButton variant="secondary" size="sm" type="button" className="text-xs text-emerald-400 hover:underline bg-transparent border-none shadow-none px-0 py-0 h-auto">Forgot password?</InterstateButton>
              </div>
            </div>
            {error && <div className="text-xs text-red-400 mb-2 text-center">{error}</div>}
            {success && <div className="text-xs text-emerald-400 mb-2 text-center">{success}</div>}
            <InterstateButton type="submit" fullWidth loading={loading} className="mb-3">Login</InterstateButton>
          </form>
        ) : (
          <form onSubmit={handleRegister}>
            <div className="text-xl font-bold mb-4 text-center">Sign Up</div>
            <div className="mb-3">
              <label className="block text-xs mb-1">Username</label>
              <input
                type="text"
                className="w-full px-3 py-2 rounded-3xl border border-neutral-700 text-xs mb-2 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="Enter username"
                value={username}
                onChange={e => setUsername(e.target.value)}
                required
              />
              <label className="block text-xs mb-1">Email</label>
              <input
                type="email"
                className="w-full px-3 py-2 rounded-3xl border border-neutral-700 text-xs mb-2 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="Enter email"
                value={email}
                onChange={e => setEmail(e.target.value)}
                required
              />
              <label className="block text-xs mb-1">Password</label>
              <input
                type="password"
                className="w-full px-3 py-2 rounded-3xl border border-neutral-700 text-xs mb-2 focus:outline-none focus:ring-2 focus:ring-emerald-500"
                placeholder="Enter password"
                value={password}
                onChange={e => setPassword(e.target.value)}
                required
              />
            </div>
            {error && <div className="text-xs text-red-400 mb-2 text-center">{error}</div>}
            {success && <div className="text-xs text-emerald-400 mb-2 text-center">{success}</div>}
            <InterstateButton type="submit" fullWidth loading={loading} className="mb-3">Sign Up</InterstateButton>
            <div className="text-center text-xs mt-3 text-neutral-400">
              Already have an account?{' '}
              <button className="text-emerald-400 hover:underline bg-transparent border-none shadow-none px-0 py-0 h-auto" onClick={() => setMode('login')}>Login</button>
            </div>
            <div className="text-xs text-neutral-500 mt-4 text-center">
              By creating an account, you agree to Interstate's{' '}
              <a href="#" className="underline">Privacy Policy</a> and{' '}
              <a href="#" className="underline">Terms of Service</a>.
            </div>
          </form>
        )}
        </>
      )}
      <hr  className="mt-4 border-neutral-600"/>
      <div className="flex flex-col items-center gap-2 mt-4">
        {googleClientId ? (
          <GoogleOAuthProvider clientId={googleClientId}>
            <div className={`mb-1 flex flex-col items-center ${AUTH_BUTTON_WIDTH_CLASS}`}>
              {authState === AuthState.Authenticated ? (
                <div className="w-full rounded-3xl border border-neutral-700/60 bg-neutral-800/40 px-3 py-3 text-center text-sm text-neutral-200">
                  Finishing sign-in…
                </div>
              ) : clientState !== ClientState.Ready ? (
                <InterstateButton type="button" fullWidth variant="secondary" disabled>
                  <span className="flex items-center justify-center gap-2 font-normal text-sm">
                    Preparing login…
                  </span>
                </InterstateButton>
              ) : !googleNonce ? (
                <InterstateButton type="button" fullWidth variant="secondary" disabled>
                  <span className="flex items-center justify-center gap-2 font-normal text-sm">
                    {googleLoading ? 'Finishing sign-in…' : 'Generating nonce…'}
                  </span>
                </InterstateButton>
              ) : googleLoading ? (
                <InterstateButton type="button" fullWidth variant="secondary" disabled>
                  <span className="flex items-center justify-center gap-2 font-normal text-sm">
                    Signing in with Google…
                  </span>
                </InterstateButton>
              ) : (
                <div className="w-full flex justify-center">
                  <GoogleLogin
                    nonce={googleNonce}
                    onSuccess={handleGoogleSuccess}
                    onError={handleGoogleError}
                    useOneTap={false}
                    theme="outline"
                    shape="pill"
                    text="continue_with"
                    size="large"
                    width="400"
                  />
                </div>
              )}
            </div>
          </GoogleOAuthProvider>
        ) : (
          <InterstateButton type="button" fullWidth variant="secondary" disabled className={AUTH_BUTTON_WIDTH_CLASS}>
            <span className="flex items-center justify-center gap-2 font-normal text-sm">
              Google login not configured
            </span>
          </InterstateButton>
        )}

        <InterstateButton
          type="button"
          fullWidth
          variant="secondary"
          onClick={() => {
            clearAllLoadingStates();
            setShowWalletOptions(!showWalletOptions);
          }}
          disabled={phantomLoading || metamaskLoading}
          className={`flex items-center justify-between hover:bg-neutral-800 transition-colors ${AUTH_BUTTON_WIDTH_CLASS}`}
        >
          <span className="flex items-center gap-2 font-normal text-sm">
            <img src="/Phantom-Wallet-300x300.png" alt="Phantom" className="w-6 h-6 rounded-[100px]" />
            Continue with crypto wallet 
          </span>
          <div className={`flex items-center justify-center transform transition-transform duration-200 ${showWalletOptions ? 'rotate-180' : ''}`}>
            <svg className="w-4 h-4 text-neutral-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
            </svg>
          </div>
        </InterstateButton>
      </div>
      
      {walletError && <div className="text-xs text-red-400 mt-4 text-center">{walletError}</div>}


      {/* Wallet Options with Better Design */}
      {showWalletOptions && (
        <div className={`mt-4 overflow-hidden transition-all duration-300 ease-in-out ${AUTH_BUTTON_WIDTH_CLASS}`}>
          <div className="bg-neutral-800/50 rounded-xl p-4 border border-neutral-700/50">
            <div className="text-xs text-neutral-400 mb-3 font-medium">Choose your wallet</div>
            <div className="space-y-2">
              {/* MetaMask */}
              <button
                type="button"
                className={`w-full flex items-center justify-between p-3 rounded-lg transition-all duration-200 bg-neutral-700/50 hover:bg-neutral-600/50 border border-neutral-600/50 hover:border-neutral-500/50 ${metamaskLoading ? 'opacity-50 cursor-not-allowed' : ''}`}
                onClick={() => {
                  setPhantomLoading(false);
                  setGoogleLoading(false);
                  handleMetamaskLogin();
                }}
                disabled={metamaskLoading}
              >
                <div className="flex items-center gap-3">
                  <img src="/MetaMask-icon-fox.svg" alt="MetaMask" className="w-5 h-5" />
                  <div className="flex flex-col items-start">
                    <span className="font-medium text-sm">MetaMask</span>
                    {metamaskLoading && (
                      <span className="text-xs text-yellow-400">Connecting...</span>
                    )}
                  </div>
                </div>
              </button>

              {/* Phantom */}
              <button
                type="button"
                className={`w-full flex items-center justify-between p-3 rounded-lg transition-all duration-200 bg-neutral-700/50 hover:bg-neutral-600/50 border border-neutral-600/50 hover:border-neutral-500/50 ${phantomLoading ? 'opacity-50 cursor-not-allowed' : ''}`}
                onClick={() => {
                  setMetamaskLoading(false);
                  setGoogleLoading(false);
                  handlePhantomLogin();
                }}
                disabled={phantomLoading}
              >
                <div className="flex items-center gap-3">
                  <img src="/Phantom-Wallet-300x300.png" alt="Phantom" className="w-5 h-5 rounded-full" />
                  <div className="flex flex-col items-start">
                    <span className="font-medium text-sm">Phantom</span>
                    {phantomLoading && (
                      <span className="text-xs text-yellow-400">Connecting...</span>
                    )}
                  </div>
                </div>
              </button>

            </div>
          </div>
        </div>
      )}
        </>
      )}
    </InterstatePopout>
  );
}
